### ISSUE TITLE
Browserify not automatically installed

### ISSUE THREAD

**Issue by mdcanham** [Pinpickle/tight#18]
Got the following error during install. Browserify is installed globally, manually installing Browserify, after Yeoman had done its thing, fixed the issue.

```
Building your theme
module.js:338
    throw err;
    ^
Error: Cannot find module 'browserify'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/matthewcanham/Documents/Development/Websites/theme/gulp.js:20:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by Pinpickle** [comment]
This isn't a fault of Browserify not being installed, but incorrectly required. It was outside of the `{% if theme.js == 'browserify %}` block. That's fixed now.

This is difficult to add tests for, as dependencies aren't deleted between test cases (faster tests). I think a good solution would be to delete dependencies that aren't in the current project.
